on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: main

name: Post Tweets

jobs:
  render:
    name: Reply to Twitter Mentions
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install gdal
        run: brew install gdal
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("dplyr","ggplot2","stringr","tidycensus","tigris","viridis","rtweet"))'
      - name: Run the bot
        env: 
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: Rscript bot.R